// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Timer
{
	public partial class TimersTableViewController : UITableViewController
	{
		public TimersTableViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            NavigationController.NavigationBar.PrefersLargeTitles = true;

            TableView.Source = new TimersTableViewSource(this);
        }
    }
}
