// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Timer
{
	public partial class TimerDetailViewController : UIViewController
	{
		public TimerDetailViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
