// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace Timer
{
    internal class TimersTableViewSource : UITableViewSource
    {
        private readonly UINavigationController navigationController;

        List<float> timers;
        private TimersTableViewController timersTableViewController;
        const string TimerCellIdentifier = "TimerCell";

        public TimersTableViewSource(TimersTableViewController timersTableViewController)
        {
            this.timersTableViewController = timersTableViewController;

            timers = new List<float>() { 0.3f, 0.25f, 2.0f };
        }

        public override nint RowsInSection(UITableView tableview, nint section)
        {
            return timers.Count;
        }

        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            UITableViewCell cell = tableView.DequeueReusableCell(TimerCellIdentifier);

            string cellTitle = $"Phase {indexPath.Row}";
            float time = timers[indexPath.Row];

            if (cell == null)
            {
                cell = new UITableViewCell(UITableViewCellStyle.Subtitle, TimerCellIdentifier);
            }

            cell.TextLabel.Text = cellTitle;
            cell.DetailTextLabel.Text = $"{time} mn";

            return cell;
        }

        public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
        {
            timersTableViewController.PerformSegue("showPlayerSegue", null);
        }
    }
}