// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using VIewModels.Interfaces;

namespace Timer
{
	public partial class TimerDetailViewController : UIViewController
	{
		public TimerDetailViewController (IntPtr handle) : base (handle)
		{
		}

        ITimerDetailViewModel ViewModel => AppDelegate.Locator.TimerDetailViewModel;

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            ViewModel.ReloadContext();

            nameLabel.Text = ViewModel.CurrentTimer.Name;
            durationLabel.Text = ViewModel.CurrentTimer.Duration.ToString();
        }
    }
}
